# Generated by Django 4.2.4 on 2023-09-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0004_play_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["row", "seat"]},
        ),
        migrations.AlterField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("performance", "row", "seat")},
        ),
    ]
